name: Run a lottery
on: [workflow_dispatch]
jobs:
  choose-winner:
    runs-on: ubuntu-latest
    name: Pulling a winner
    steps:
    - uses: actions/checkout@v2
    - run: | 
      chmod +x ./data/winner.sh
      ./data/winner.sh